### ISSUE TITLE
Happens when opening Almanac 2.0.1

### ISSUE THREAD

**Issue by BurroTile** [RustyMods/Almanac#2]
Valheim: V0.217.25
BepExPack_Valheim-5.4.2200

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
Almanac.UI.Patches+OnOpenTrophiesPatch.SetUnknownItems (Almanac.AlmanacPlugin+Toggle toggle, System.String id, System.Collections.Generic.List`1[T] list) (at <87041be3b0974f2d92094f60b8bf6a94>:0)
Almanac.UI.Patches+OnOpenTrophiesPatch.Postfix (InventoryGui __instance) (at <87041be3b0974f2d92094f60b8bf6a94>:0)
(wrapper dynamic-method) InventoryGui.DMD<InventoryGui::OnOpenTrophies>(InventoryGui)
UnityEngine.Events.InvokableCall.Invoke () (at <80fe1a4e36fe44618284312cb721a597>:0)
UnityEngine.Events.UnityEvent.Invoke () (at <80fe1a4e36fe44618284312cb721a597>:0)
UnityEngine.UI.Button.Press () (at <e97aac8d17514bea83fadfd039e9187a>:0)
UnityEngine.UI.Button.OnPointerClick (UnityEngine.EventSystems.PointerEventData eventData) (at <e97aac8d17514bea83fadfd039e9187a>:0)
UnityEngine.EventSystems.ExecuteEvents.Execute (UnityEngine.EventSystems.IPointerClickHandler handler, UnityEngine.EventSystems.BaseEventData eventData) (at <e97aac8d17514bea83fadfd039e9187a>:0)
UnityEngine.EventSystems.ExecuteEvents.Execute[T] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.ExecuteEvents+EventFunction`1[T1] functor) (at <e97aac8d17514bea83fadfd039e9187a>:0)
UnityEngine.EventSystems.EventSystem:Update()

**Comment by RustyMods** [comment]
Thank you for notice. Ill see what I can do. If possible. Can you share your full log so I can figure out origine of issue. Most likely a mod conflict.

**Comment by BurroTile** [comment]
It very well may be. Thank you and thanks for the awesome mod!  

[LogOutput.log](https://github.com/RustyMods/Almanac/files/13047413/LogOutput.log)
