### ISSUE TITLE
Incompatibility with Auga UI

### ISSUE THREAD

**Issue by phantom745** [RustyMods/Almanac#5]
Don't know where to put this honestly, but when using the Auga UI overhaul the trophies button is removed so the almanac cant be accessed. I think that mod and this one go very well together and would love to see a tab on his character element for the almanac. Again more of a suggestion than an issue, but wasn't sure where to put it.
![20240201234753_1](https://github.com/RustyMods/Almanac/assets/4897085/326e6f3a-d7bd-40bc-a0f0-5c85e51933f7)

**Comment by RustyMods** [comment]
Auga and Almanac are incompatible as the methods I use to create my almanac depends on vanilla UI structure. Auga changes almost everything about the UI so I end up with a slew of errors. Unfortunately at this time, I do not see a way to make Auga and Almanac compatible

**Comment by phantom745** [comment]
I figured. Thanks for the response.
